### ISSUE TITLE
Files missing from Collection 3165

### ISSUE THREAD

**Issue by perronea** [DCAN-Labs/nda-abcd-s3-downloader#24]
@mriedel56 has noted that some event timing files, motion files, and volumetric bold data are missing from a small subset of subjects. We have confirmed that those files are indeed missing and it's not an issue with the datastructure_manifest.txt or the code base. We suspect that there was an issue with the initial upload of these files and we are working to recover and upload them as quickly as possible.

**Comment by perronea** [comment]
The desired files have been uploaded to the NDA, they just haven't been released publicly yet. We will close this issue when they are released by the NDA.

**Comment by arueter1** [comment]
Hi There! We have uploaded these files, but are waiting on the NDA to release these data. If you still need these data, please email ndahelp@mail.nih.gov with the collection # and data you are looking for. I am going to close this issue as the best resolution is for you to check with the NDA about switching our uploaded files to public status. If you have further issues, feel free to reopen.
