### ISSUE TITLE
zero-lag pearson correlation values above 1 in connectivity matrices

### ISSUE THREAD

**Issue by kimberlylray** [DCAN-Labs/nda-abcd-s3-downloader#25]
Thanks so much for sharing the Collection 3165 - ABCD-BIDS Community Collection.  I am interested in using the resting state functional connectivity estimates from the Gordon atlas.  Reading the documentation on the preprocessing pipeline ([https://collection3165.readthedocs.io/en/stable/pipeline/#stage-10-connectivity-matrix-generation](https://collection3165.readthedocs.io/en/stable/pipeline/#stage-10-connectivity-matrix-generation)), I see that functional connectivity estimates are based on zero-lag pearson correlation. Typically correlation values range from -1 to 1, can you explain why there are connectivity values above 1 in the resting state adjacency matrices? Im wondering if these values have possibly been normalized? 
Thanks! - Kim

**Comment by ericfeczko** [comment]
Good question!

A variance stabilizing transform was applied to the correlations, z = arctanh(r), where r is the lag-zero pearson corrrelation. 

The inverse can be applied to recover the original correlation, r = tanh(z). I will make sure to update the documentation accordingly.

**Comment by kimberlylray** [comment]
ok that makes much more sense, thanks for the quick response!

**Comment by ericfeczko** [comment]
No problem. Thanks for catching the documentation missing, I've updated the readthedocs and pushed the changes; once the autobuild completes it should be updated by tomorrow at the latest :)
