### ISSUE TITLE
Failed downloads

### ISSUE THREAD

**Issue by macmitch** [DCAN-Labs/nda-abcd-s3-downloader#26]
Hello, I am running into an issue where 4 specific files are not downloading. I have relaunched the downloader tool and those 4 files are again the only files in the failed_downloads.txt output. The files are "*task-rest_bold_desc-filtered_timeseries.dtseries.nii" from four different subjects. I am wondering if anyone is aware of particular issues with these files specifically. Thanks!

**Comment by arueter1** [comment]
Hi @macmitch - apologies for the delay in responding, our lab is slammed! I have assigned two folks from our lab who may be able to help you out. We will get back to you as soon as we are able.

**Comment by perronea** [comment]
@macmitch It seems this has fallen off our radar. In order to troubleshoot this we will need to know the subject IDs. Could you please send them to me in a .txt file at perr0372@umn.edu? Thank you

**Comment by arueter1** [comment]
@macmitch closing this item since we haven't heard back. Feel free to respond and reopen the issue if you are still running into difficulties.
