### ISSUE TITLE
Failed to create NDA token

### ISSUE THREAD

**Issue by CFGEIER** [DCAN-Labs/nda-abcd-s3-downloader#28]
Hello,
I'm getting the error message below when trying to use the downloader. (Confirmed that username and password were entered correctly.). Would appreciate any help - thanks!  

cfg2$ python3 download.py -i ~/Downloads/datastructure_manifest.txt -o /Volumes/Geier_HD/ -d data_ptseries.txt 

Derivatives downloader called at 2022:01:28 18:36 with:

 

Enter your NIMH Data Archives username: geiercf

Enter your NIMH Data Archives password: 

/Users/cfg2/Downloads/nda-abcd-s3-downloader-master/src/nda_aws_token_maker.py:23: SyntaxWarning: "is" with a literal. Did you mean "=="?

  if len(sys.argv) is 3:  # [0] is self, [1] is username, [2] is password, so 3

Failed to create NDA token.

Failed to create NDA token using the username and decrypted password from /Users/cfg2/.abcd2bids/config.ini.

**Comment by perronea** [comment]
The nda token maker is a little out of date. We need to update this repository with the latest token generation method from the ndar toolkit. I'll notify you as soon as this update is complete.

**Comment by perronea** [comment]
I've replaced the token generator and refactored the download method to leverage the NDA package API in a way that avoids the Timeout errors that users were reporting with downloadcmd. Please follow the new documentation on the v1.0.0 pre-release of this repository to access Collection 3165 and please open a new issue if you encounter any further problems with this utility.
