### ISSUE TITLE
Collection is not named "DCAN Labs ABCD-BIDS MRI pipeline inputs and derivatives" in NDA

### ISSUE THREAD

**Issue by dmoracze** [DCAN-Labs/nda-abcd-s3-downloader#30]
Unless I'm misunderstanding something, step 4 of your README should instruct users to search the NDA for "DCAN Labs ABCD-BIDS Community Collection (ABCC)" rather than "DCAN Labs ABCD-BIDS MRI pipeline inputs and derivatives".

**Comment by perronea** [comment]
Thank you for catching this error in the documentation. It has been corrected.
