### ISSUE TITLE
All but func data ignored

### ISSUE THREAD

**Issue by smeisler** [DCAN-Labs/nda-abcd-s3-downloader#31]
Hello,

I wanted to test getting raw data for a few subjects. I input a few names into a text file which was passed into the `-s` flag and parsed correctly. For the `-d` flag I made an altered copy of `data_subsets.txt` that contained the following fields:

```
inputs.anat.T1w
inputs.anat.T2w
inputs.dwi.dwi
inputs.fmap.all
inputs.func.task-MID
inputs.func.task-nback
inputs.func.task-rest
inputs.func.task-SST
sourcedata.func.task_events
```

The result from the download command, which finished without any error messages, only included functional outputs. Checking the logs revealed no failed downloads, but also no anat/dwi downloads in the successful downloads either. I am fairly certain these subjects had DWI and anat data pass QC.

What do you think the best way for me to proceed is?

Thanks,
Steven

**Comment by begim-f** [comment]
Hi @smeisler , 

Apologies for the delayed reply. I'd like to clarify that we've made updates to the documentation. The issue stemmed from the README file in this repository under the Usage section, which referenced the '-d' flag. However, please note that the appropriate flag to use in the 'download.py' script is '-b'.

Thank you!
