### ISSUE TITLE
Issue authenticating credentials

### ISSUE THREAD

**Issue by mvedechkina** [DCAN-Labs/nda-abcd-s3-downloader#32]
Hello, 

I seem to be running into issues downloading the data. Specifically, I'm running into an authentication issue. See below for the error message when I enter my credentials:

_SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(sys.argv) is 3:  # [0] is self, [1] is username, [2] is password, so 3
ERROR:root:response had error message: Invalid username and/or password
aws_access_key_id= XXX
aws_secret_access_key=XXX
security_token=XXX_

I double-checked that the password and username were correct and, as seen above, an AWS access key is still being created when I enter the correct credentials. When I tried using a different incorrect username, the NDA token failed to be created. Any idea why my log-in details might not be working? 

Thank you for your help!
Maria

**Comment by perronea** [comment]
I've replaced the token generator and refactored the download method to leverage the NDA package API in a way that avoids the Timeout errors that users were reporting with downloadcmd. Please follow the new documentation on the v1.0.0 pre-release of this repository to access Collection 3165 and please open a new issue if you encounter any further problems with this utility.
