### ISSUE TITLE
Initial config file fail

### ISSUE THREAD

**Issue by drewwint** [DCAN-Labs/nda-abcd-s3-downloader#33]
I am running into the same issue. However, this issue persists even when I specify the file's location using the -c flag suggested above. Is there another workaround?

![error](https://user-images.githubusercontent.com/53614162/178044385-e564e038-4c21-4568-8d9c-40282f5bf05a.png)

_Originally posted by @drewwint in https://github.com/DCAN-Labs/nda-abcd-s3-downloader/issues/4#issuecomment-1179229124_

**Comment by perronea** [comment]
I've replaced the token generator and refactored the download method to leverage the NDA package API in a way that avoids the Timeout errors that users were reporting with downloadcmd. Please follow the new documentation on the v1.0.0 pre-release of this repository to access Collection 3165 and please open a new issue if you encounter any further problems with this utility.
