### ISSUE TITLE
Validation of Downloads

### ISSUE THREAD

**Issue by BrynGibson** [DCAN-Labs/nda-abcd-s3-downloader#34]
I am attempting to validate to validate the download of this entire dataset. I have run the download script using the data subsets file provided. The script crashed a few times and needed to be restarted. I believe that the script should have checked if any files are missing when building the download list. However, I would like to confirm that all the available files are downloaded correctly. The download folder is currently around 66TB, is this about the correct size for all subjects and all data subsets? Or is there a list of all available files and/or hashes than I can use to validate the downloaded files are correct?

Regards,
Bryn

**Comment by BrynGibson** [comment]
For example, the file participants.json or participants.tsv, which should be at the top level of the file structure appears to be missing.

**Comment by ericfeczko** [comment]
I think that's a little short if one is downloading the entire dataset. 

The datastructure_manifest.txt should contain a list of all files available through the S3 and can be used to identify missing files. @perronea may have some scripts that can be used to validate -- we are in the process of making them easy to use and accessible before providing a repository for them.

**Comment by ericearl** [comment]
@ericfeczko Has the big version 2 release made it out of NDA QA yet?  If not, then 66TB sounds about right from what it used to be,

And @BrynGibson , the participants files are downloaded separate/directly from the NDA collection 3165 page.  More info here:

https://collection3165.readthedocs.io/en/stable/recommendations/#2-the-bids-participants-files-and-matched-groups

> They are available for download on [the main NDA Collection 3165 page](https://nda.nih.gov/edit_collection.html?id=3165).

**Comment by BrynGibson** [comment]
Thanks have downloaded the participants files separately now.

I have attempted to parse the datastructure_manifest.txt, I used the associated file column to build relative file paths and compared them against my downloaded location. It seems as though I am missing 8655 files. These files appear to mostly be in this format with run-3 or run-4
```
derivatives/abcd-hcp-pipeline/sub-xxxxx/ses-baselineYear1Arm1/func/sub-xxxxx_ses-baselineYear1Arm1_task-rest_run-3_space-MNI_bold.nii.gz,
derivatives/abcd-hcp-pipeline/sub-yyyyy/ses-baselineYear1Arm1/func/sub-yyyyy_ses-baselineYear1Arm1_task-rest_run-4_space-MNI_bold.nii.gz,
```
I have attempted redownload these files using the rerunning provided download script but get a 403 error.

```
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
Command failed: mkdir -p /local/path/derivatives/abcd-hcp-pipeline/sub-zzzzz/ses-baselineYear1Arm1/func ; aws s3 cp s3://NDAR_Central_1/submission_33328/derivatives/abcd-hcp-pipeline/sub-zzzzz/ses-baselineYear1Arm1/func/sub-zzzzz_ses-baselineYear1Arm1_task-rest_run-4_space-MNI_bold.nii.gz /local/path/derivatives/abcd-hcp-pipeline/sub-zzzzz/ses-baselineYear1Arm1/func/sub-zzzzz_ses-baselineYear1Arm1_task-rest_run-4_space-MNI_bold.nii.gz --profile NDA

**Comment by BrynGibson** [comment]
@ericearl is there any update on access to the missing files I mentioned?

Thanks, 
Bryn

**Comment by ericearl** [comment]
@BrynGibson Sorry, but the person who can answer that question is probably either @ericfeczko or @perronea since I haven't been in that lab for the last year and a half.  I just remember some of the historical things that happened...

**Comment by BrynGibson** [comment]
@ericearl Understood. Thanks for your input anyway. I will wait and see if anyone else can help.

**Comment by perronea** [comment]
@BrynGibson This data was uploaded over a year ago and finally made public a couple months ago. There shouldn't be any permissions issues as long as you have access to the collection. I've contacted the NDA help desk about this for you. I'll update you here when they get back to me.

**Comment by BrynGibson** [comment]
I have just tried downloading the dataset again as there has been some updates to the dataset since I first begun the download job. It seems there was 4000 more files that were successfully downloaded, however there are about 10,000 files in the failed downloads log. Many of these files seem to be of the format
```
derivatives/abcd-hcp-pipeline/sub-xxxxx/ses-baselineYear1Arm1/func/sub-xxxxx_ses-baselineYear1Arm1_task-rest_run-3_space-MNI_bold.nii.gz,
derivatives/abcd-hcp-pipeline/sub-yyyyy/ses-baselineYear1Arm1/func/sub-yyyyy_ses-baselineYear1Arm1_task-rest_run-4_space-MNI_bold.nii.gz,
```
Perhaps it would be useful if I shared my failed download logs with you privately, maybe via email? So that you could take a look and see if it is clear why the download is failing on these files. @perronea @ericfeczko 

Many thanks,
Bryn

**Comment by perronea** [comment]
@BrynGibson I opened an NDA help desk ticket about this 12 days ago, but I haven't received a response. I'll ping them again right now. Thank you for the reminder!

**Comment by perronea** [comment]
@BrynGibson it appears the NDA has finally deprecated the backend of their legacy downloader for security reasons. We used this backend to create tokens that enabled users to download data directly from s3. Instead you must create a data package on the NDA's website with the desired submissions and download the data with the Download Manager beta. The submissions that you will want to download are 3317-3335.

I would be happy to set up a call to discuss this in further detail if you like. Email me at perr0372@umn.edu

**Comment by perronea** [comment]
To clarify, this only affects submissions after a certain date. I am currently working with the NDA to figure out a programatic work around.
