### ISSUE TITLE
Trouble with credentials

### ISSUE THREAD

**Issue by samniv** [DCAN-Labs/nda-abcd-s3-downloader#36]
Hi,
   I am trying to access the data from DCAN lab- ABCD; i used the following code - however, it results in a config error. 
First I ran without giving -c details
code: /Users/samson.nivins/Documents/ABCD/download.py -i s3_file.csv -o /Users/samson.nivins/Documents/ABCD/ -s subject_list_file.txt -l /Users/samson.nivins/Documents/ABCD/subject_list_file.txt -d basenames_file.txt   -p 1

It results in the following error-
/Users/samson.nivins/Documents/ABCD/src/nda_aws_token_maker.py:23: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(sys.argv) is 3:  # [0] is self, [1] is username, [2] is password, so 3
Failed to create NDA token.
Failed to create NDA token using the username and decrypted password from /Users/samson.nivins/.abcd2bids/config.ini.

Any leads will be helpful.

Thanks

**Comment by zhangyubrain** [comment]
Still not working. In #35, perronea mentioned that the data now can only be downloaded from NDA data package. Any better way?

**Comment by ericfeczko** [comment]
The underlying problems reflect NDA infrastructure constraints and the need for creative solutions to overcome it. 

@perronea is hard at work on a collaborative solution with the NDA which should finally resolve this issue. We are currently in the final stages of documentation/testing before updating the downloader. 

Long story short, I am optimistic that we will finally have a specific-file solution with clear instructions in the coming month or two. 

Thank you for leveraging the github board for raising these issues, and please continue to do so. Public awareness of these limitations helps the NDA and its collaborators to better understand issues affecting users and how to address them :)

**Comment by perronea** [comment]
@samniv I've replaced the token generator and refactored the download method to leverage the NDA package API. Please follow the new documentation on the v1.0.0 pre-release of this repository to access Collection 3165.
