### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error:  for url: https://nda.nih.gov/api/package/XXX/files

### ISSUE THREAD

**Issue by kahinimehta** [DCAN-Labs/nda-abcd-s3-downloader#48]
Hi @perronea , hope you're well. Following up from the issue discussed in #46 , I added the package dataset ID to the call, using the following code: 
`nda-abcd-s3-downloader % python download.py -m /Users/kahinim/Desktop/Package_1210637/datastructure_manifest.txt -s /Users/kahinim/Desktop/subject.txt -o /Users/kahinim/Desktop -dp 1210637`
  but am still getting the same traceback as before: 

<img width="907" alt="Screen Shot 2023-03-13 at 10 28 00 PM" src="https://user-images.githubusercontent.com/68132139/224877186-a7ad1b16-0c00-45e9-9b0e-cc0a55d1397c.png">

I tried this with a few different packages but the error message did not change. I was wondering if you had any guidance on why this might be? Thanks again for your patience and advice!

**Comment by perronea** [comment]
Okay this is a slightly different error. You actually need to make 2 data packages 1) where you select "Include associated data" when creating the package - this is the one that you will specify in your download command, and 2) where you DO NOT select "Include associated data" - this is the one that you used to download the datastructure manifest from.

I know it's an annoying seemingly pointless extra step. I'm working with the NDA to get it fixed, but until then this is really the only way.

Let me know if that solves your problem. If so I'll work on making this more clear in the documentation.

**Comment by kahinimehta** [comment]
Hi @perronea thank you - it does seem clear in the documentation, but the package I selected should be the one with no associated data - I created two versions of the package. Is there any other reason I could be getting this error?

**Comment by kahinimehta** [comment]
Ahh, I see!  Yes, that seems to have worked - thanks so much, again @perronea
