### ISSUE TITLE
README missing installation instructions

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/nda-abcd-s3-downloader#49]
Whether you recommend something like...

```shell
git clone https://github.com/DCAN-Labs/nda-abcd-s3-downloader.git
python3 -m pip install -r nda-abcd-s3-downloader/requirements.txt --user
```

... or something else, the README does not include an installation section and an expected version of Python. For instance, I am on Python 3.7.5 and I can't therefore install numpy 1.24.2.

**Comment by LuciMoore** [comment]
repo is no longer being maintained!
