### ISSUE TITLE
Subprocess call to NDA_TOKEN_GENERATOR returns a FileNotFoundError

### ISSUE THREAD

**Issue by obenshaindw** [DCAN-Labs/nda-abcd-s3-downloader#5]
When running the nda-abcd-s3-downloader using a valid config file, a FileNotFoundError occurs when the script makes a subprocess call to the nda_aws_token_generator.py python script.
```
c:\Users\obenshaindw\Documents\Code\Python\nda-abcd-s3-downloader>python download.py -i datastructure_manifest.txt -o c:\Users\obenshaindw\Downloads -c ./abcd-nda-settings.cfg
Derivatives downloader called at 2020:01:04 00:28 with:
Traceback (most recent call last):
  File "download.py", line 379, in <module>
    _cli()
  File "download.py", line 108, in _cli
    make_nda_token(args.credentials)
  File "download.py", line 309, in make_nda_token
    password
  File "C:\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by perronea** [comment]
I've replaced the token generator and refactored the download method to leverage the NDA package API in a way that avoids the Timeout errors that users were reporting with downloadcmd. Please follow the new documentation on the v1.0.0 pre-release of this repository to access Collection 3165 and please open a new issue if you encounter any further problems with this utility.
