### ISSUE TITLE
The keyring stuff in the README is under "Recommended Inputs" instead of "Requirements"

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/nda-abcd-s3-downloader#50]
I am trying out the latest code here and followed the REDAME instructions to produce a datastructure_manifest.txt in a package without associated files and a separate 150TB+ package including associated files. Unfortunately when I try to use the download.py, I get:

```shell
> python3 download.py -dp ANONYMIZEDPACKAGEID -m ../datastructure_manifest.txt -o pconns -l logs -b data_subsets.pconns.txt
Enter your NIMH Data Archives username: ienteredmyusernamehere
sys:1: DtypeWarning: Columns (0,1,2) have mixed types.Specify dtype option on import or set low_memory=False.
Collecting Subjects
Logger Collecting Subjects
        Subjects:       All subjects
Traceback (most recent call last):
  File "download.py", line 89, in <module>
    main()
  File "download.py", line 85, in main
    ABCC_Downloader = Downloader(args)
  File "/lever/data/abcd_downloads/test_new_downloader/nda-abcd-s3-downloader/src/Downloader.py", line 172, in __init__
    self.start()
  File "/lever/data/abcd_downloads/test_new_downloader/nda-abcd-s3-downloader/src/Downloader.py", line 229, in start
    for package_file_list in self.generate_download_file_ids():
  File "/lever/data/abcd_downloads/test_new_downloader/nda-abcd-s3-downloader/src/Downloader.py", line 246, in generate_download_file_ids
    package_files = self.query_package_files_by_s3_url(self.s3_links_arr[batch_start:batch_end])
  File "/lever/data/abcd_downloads/test_new_downloader/nda-abcd-s3-downloader/src/Downloader.py", line 258, in query_package_files_by_s3_url
    response = post_request(url, list(s3_path_list), auth=self.auth, error_handler=HttpErrorHandlingStrategy.reraise_status)
  File "/lever/data/abcd_downloads/test_new_downloader/nda-abcd-s3-downloader/src/utils.py", line 228, in post_request
    error_handler(tmp)
  File "/lever/data/abcd_downloads/test_new_downloader/nda-abcd-s3-downloader/src/utils.py", line 82, in reraise_status
    response.raise_for_status()
  File "/home/earlea/.local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://nda.nih.gov/api/package/ANONYMIZEDPACKAGEID/files
```

I suspect this is due to the volume of the package query's returned JSON and some kind of timeout. So I emailed NDA help desk first to make sure I wasn't doing something silly...

(As an aside, I also noticed it didn't prompt me for my password, so I don't know if that was intended or not.)

When I told the NDA help desk I couldn’t get my package file listing to work outside of swagger (because swagger succeeded by limiting my response to 30 returned results), they said:

> I suspect that collection 3165 has >10M files. We cannot return that many files at one time so the files need to be requested in 'pages'. This is a pretty common thing for APIs to do. There should be a pageNumber query parameter, as well as a size parameter, in the get-package-files endpoint. If [you] set the page number to 2 and re-execute the request, it should return the next 30 results. The value of the size parameter is 30 by default.
>
> With a package that contains as many files as collection 3165, I imagine it will take a long time to get the whole listing. If you are doing this for an application, I would recommend that you do this once and save the results so that you do not have to re-retrieve the file list in the future.

What would you recommend as next steps to make this work? Does the Downloader currently try to read the whole thing or does it try to read in smaller pages at a time then compile them?

**Comment by ericearl** [comment]
@perronea I found the problem, and it was the README... By which I mean:

The steps after **Requirements** are under the heading **Recommended Inputs** so I stopped reading because I thought I had done everything required of me based on my previous knowledge of the tool. Unfortunately, the **NDA Credentials** heading is actually a requirement, not just recommended. After I performed the keyring stuff, it worked! So I'm going to change the title of this issue to something about the README instead.

Please add the NDA Credentials section about keyring as a requirement instead of just placing it in the recommended section. Thanks!

**Comment by perronea** [comment]
Great point! The NDA credential part is pretty critical and should be at the top of the usage documentation.

**Comment by rosemccollum** [comment]
Moved the NDA credential section to be under requirements
