### ISSUE TITLE
download.py missed all of the fMRIprep files even though they could be downloaded one by one using  downloadcmd 

### ISSUE THREAD

**Issue by narunpat** [DCAN-Labs/nda-abcd-s3-downloader#52]
We have tried to use download.py to download fMRIprepped data from a ABCC package, we created on 27th March 23 with all evaluated data. However, it seems that the `download.py` missed all of the fMRIprep files.

[NOTE I changed subject ID to XXXXXXXX, package ID with associated files to YYYYYYY and package ID with metadata to ZZZZZZZ] 

Here we tried to download all of the data from one subject. Here we gave the subject id in a textfile, `subject_list.txt`.

`python3 download.py -dp YYYYYYY -m /media/hcs-sci-psy-narun/ABCC_March2023/Package_ZZZZZZZ/datastructure_manifest.txt -o /media/hcs-sci-psy-narun/ABCC -s subject_list.txt -wt 10 `

We got the files listed under the attached [sub-NDARINVXXXXXXXX-find_files.txt](https://github.com/DCAN-Labs/nda-abcd-s3-downloader/files/11174987/sub-NDARINVXXXXXXXX-find_files.txt). However, these are either BIDS files or abcd-hcp-pipeline files. None of the fmriprepped files was downloaded. This is despite that the `datastructure_manifest.txt` has many fmriprepped files for this subject, see [sub-NDARINVXXXXXXXX-datastructure_manifest.txt](https://github.com/DCAN-Labs/nda-abcd-s3-downloader/files/11174986/sub-NDARINVXXXXXXXX-datastructure_manifest.txt) attached.

We then tried using the `downloadcmd` command from nda-tools to download the fmriprepped files. It works on one file:

`downloadcmd -dp YYYYYYY -u narunpat -d /media/hcs-sci-psy-narun/NDA -t test.txt`

Note the `test.text` has one line, which is 

> s3://NDAR_Central_1/submission_33608/derivatives/fmriprep/sub-NDARINVXXXXXXXX/ses-baselineYear1Arm1/func/sub-NDARINVXXXXXXXX_ses-baselineYear1Arm1_task-rest_run-4_space-fsnative_hemi-R_bold.func.gii

we got this file. And the message from nda is below: 

> Running NDATools Version 0.2.24
> Getting Package Information...
> Package-id: YYYYYYY
> Name: ABCConlyEvaluatedDataMarch2023
> Has associated files?: Yes
> Number of files in package: 4066372
> Total Package Size: 153.13TB
> Downloading files from package YYYYYYY matching regex sub-NDARINVXXXXXXXX
> S3 links for files that failed to download will be written out to /home/william/NDA/nda-tools/downloadcmd/logs/failed_s3_links_file_20230406T113149.txt. You can attempt to download these files later by running: 
> downloadcmd -dp YYYYYYY --file-regex sub-NDARINVXXXXXXXX -u narunpat -d /media/hcs-sci-psy-narun/NDA -wt 10 -t "/home/william/NDA/nda-tools/downloadcmd/logs/failed_s3_links_file_20230406T113149.txt
> Beginning download of files from package matching sub-NDARINVXXXXXXXX using 10 threads

Note, we also tried using the `downloadcmd` command from nda-tools to download all of the files from this subject using `--file-regex`, but it failed with 504 Server Error.

> downloadcmd -dp YYYYYYY -u narunpat -wt 10 -d /media/hcs-sci-psy-narun/NDA --file-regex 'sub-NDARINVXXXXXXXX' > ~/download_sub.txt
> Traceback (most recent call last):
>   File "/home/william/.local/bin/downloadcmd", line 8, in <module>
>     sys.exit(main())
>   File "/home/william/.local/lib/python3.10/site-packages/NDATools/clientscripts/downloadcmd.py", line 200, in main
>     s3Download.start()
>   File "/home/william/.local/lib/python3.10/site-packages/NDATools/Download.py", line 346, in start
>     for package_file_id_list in self.generate_download_batch_file_ids(completed_file_ids):
>   File "/home/william/.local/lib/python3.10/site-packages/NDATools/Download.py", line 623, in generate_download_batch_file_ids
>     files = self.get_package_files_by_page(page, self.default_download_batch_size)
>   File "/home/william/.local/lib/python3.10/site-packages/NDATools/Download.py", line 1030, in get_package_files_by_page
>     raise e
>   File "/home/william/.local/lib/python3.10/site-packages/NDATools/Download.py", line 1019, in get_package_files_by_page
>     tmp = get_request(url, auth=self.auth,
>   File "/home/william/.local/lib/python3.10/site-packages/NDATools/Utils.py", line 268, in get_request
>     return _send_prepared_request(req.prepare(), timeout=timeout, deserialize_handler=deserialize_handler, error_handler=error_handler)
>   File "/home/william/.local/lib/python3.10/site-packages/NDATools/Utils.py", line 239, in _retry
>     tmp = func(*args, **kwargs)
>   File "/home/william/.local/lib/python3.10/site-packages/NDATools/Utils.py", line 262, in _send_prepared_request
>     error_handler(tmp)
>   File "/home/william/.local/lib/python3.10/site-packages/NDATools/Utils.py", line 84, in reraise_status
>     response.raise_for_status()
>   File "/home/william/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://nda.nih.gov/api/package/YYYYYYY/files?page=1&size=50&regex=sub-NDARINVXXXXXXXX
> 

And we also got the same 504 error when changing the `--file-regex` to `fmriprep`

`downloadcmd -dp YYYYYYY --file-regex fmriprep -u narunpat -d /media/hcs-sci-psy-narun/NDA -wt 10 -t "/home/william/NDA/nda-tools/downloadcmd/logs/failed_s3_links_file_20230406T113149.txt"`

Accordingly, it seems like using the `python3 download.py` is a way to download multiple files, but it just seems to miss the fmriprepped file that `downloadcmd` can see. 

Any help will be greatly appreciated.

**Comment by ericearl** [comment]
@narunpat Fascinating! I don't know that the fmriprep-ed files are publicly shared yet, but it's interesting to me you can see them in the manifest and downloadcmd can grab a file and not the whole thing. I'm not in their lab anymore, but I'm sure @perronea or @ericfeczko or @hough129 can give you a more certain answer about if those data are even released yet.

By the way: I commend you for preserving the privacy of all those subject IDs. Not everyone remembers to do that in their GitHub issue posts.

**Comment by perronea** [comment]
@narunpat downloadcmd does not work for Collection 3165 because it is so large. That is part of the reason we had to create this separate repository for accessing our data.

The reason you weren't able to download fmriprep data using this downloader is because the fmriprep "data subsets" haven't been added to the default [data_subsets.txt](https://github.com/DCAN-Labs/nda-abcd-s3-downloader/blob/master/data_subsets.txt) file. This enables users to selectively download specific datatypes. I just uploaded a separate [frmiprep_data_subsets.txt](https://github.com/DCAN-Labs/nda-abcd-s3-downloader/blob/master/fmriprep_data_subsets.txt) to download just the fmriprep data. Add `-d <path to fmriprep_data_subsets.txt>` to your download.py command.

**Comment by williamvdv** [comment]
Thanks for that @perronea  that was most helpful.
Just another small point, it says both here `-d <path to fmriprep_data_subsets.txt>` as well as on [the front page of the github](https://github.com/DCAN-Labs/nda-abcd-s3-downloader) that you should use the `-d` flag which does not seem to work. Use of a `-b` flag does however work.

we found this out by running
`python3 download.py -h`

returning
`usage: download.py [-h] [-dp <package-id>] -m MANIFEST_FILE -o OUTPUT [-s SUBJECT_LIST_FILE] [-l LOG_FOLDER] [-b BASENAMES_FILE] [-wt <thread-count>]`

and

`-b BASENAMES_FILE, --basenames-file BASENAMES_FILE
                        Path to a .txt file containing a list of all the data basenames names to download for each subject. By default all the possible
                        derivatives and inputs will be will be used. This is the data_subsets.txt file included in this repository. To select a subset it is
                        recommended that you simply copy this file and remove all the basenames that you do not want.`

Thanks for all your hard work on this project, it is appreciated!
