### ISSUE TITLE
Only func data downloaded 

### ISSUE THREAD

**Issue by cassandrajustinelowe** [DCAN-Labs/nda-abcd-s3-downloader#54]
I am having two issues, that I think might be related. 

First, whenever I specify the data subsets - using -d and linking to the data_subsets.txt file - the command will not run. I get an error message that the data_subset file is not recognized. 

Second, and the main issue, is that only the func data are downloaded using the updated nda-abcd-s3 downloader.  None of the other data sets, including the executive summary, are not downloaded. I believe another person has highlighted a similar issue, so it might be on your radar already.

**Comment by begim-f** [comment]
Hi @cassandrajustinelowe 
Apologies for the delayed reply. Is this still an issue?

Thank you!
