### ISSUE TITLE
data_subsets.txt not working properly

### ISSUE THREAD

**Issue by YaoMeng94** [DCAN-Labs/nda-abcd-s3-downloader#56]
Hi,
    I'm downloading the ABCC using this repoistry and strictily followed the guidance. I create a data_subsets.txt file which only contain the anatomical derivatives but it still downloaded some functional data. is something I'm not doing correctly?
Thanks

**Comment by ericearl** [comment]
@YaoMeng94 Can you share the contents of your `data_subsets.txt` file and your command-line invocation?

**Comment by YaoMeng94** [comment]
Hi Eric,

 The command-line looks like this,
    python download.py -m ~/Dataset/ABCC/List/ABCC04292023Doc/datastructure_manifest.txt -o ~/Dataset/ABCC/Data -d ~/Dataset/ABCC/List/data_subsets.txt -wt 10 -l ~/Dataset/ABCC/List/Logs -dp xxxxxxx

and the content of data_subsets.txt is:
derivatives.anat.space-ACPC_dseg
derivatives.anat.space-fsLR32k_curv
derivatives.anat.space-fsLR32k_desc-smoothed_myelinmap
derivatives.anat.space-fsLR32k_myelinmap
derivatives.anat.space-fsLR32k_sulc
derivatives.anat.space-fsLR32k_thickness
derivatives.anat.space-MNI_mesh-fsLR164k_midthickness
derivatives.anat.space-MNI_mesh-fsLR32k_midthickness
derivatives.anat.space-MNI_mesh-native_midthickness
derivatives.anat.space-T1w_mesh-fsLR32k_midthickness
derivatives.anat.space-T1w_mesh-native_midthickness
derivatives.anat.stats
derivatives.anat.T1w
derivatives.anat.T2w
derivatives.anat.wmparc

But I still get a lot of functional datas downloaded into my output directory.

**Comment by YaoMeng94** [comment]
I think I have found where the problem is, the -d flag in the README of this repositriy actually not in the download.py, is -b instead. I change the command line to -b. It works fine.

**Comment by begim-f** [comment]
Thank you, @YaoMeng94 , for identifying the issue. We have promptly updated our documentation to reflect the correct information.
