### ISSUE TITLE
Implement new version of nda-tools downloadcmd

### ISSUE THREAD

**Issue by perronea** [DCAN-Labs/nda-abcd-s3-downloader#58]
The NDA has updated their downloadcmd to resolve the 50x issues from downloading data from the ABCC.  We should test their implementation and if it works leverage their download method by inputing the s3_links_arr (https://github.com/DCAN-Labs/nda-abcd-s3-downloader/blob/main/src/Downloader.py#L158) directly to downloadcmd.

**Comment by LuciMoore** [comment]
resolved
