### ISSUE TITLE
Missing files with fc derivatives 

### ISSUE THREAD

**Issue by v-karl** [DCAN-Labs/nda-abcd-s3-downloader#65]
### A short summary of a question you have for the downloader development team.

Hey! I am trying to download parcellated resting state connectivity data from the ABCC 3165 collection, but am getting a “no such file/directory error” for pconn and concatenated functional task parcellated time series (HCP2016 and Gordon atlas) data. When I use downloadcmd within the nda-tools downloader and the path to these files, I get the same error, so I am wondering if the files have been moved to a different directory?
If this is not the case, I have noticed that the full ABCC package had 159TB instead of 168 TB, so is it possible that these files are missing from the repository at the moment?

**Comment by rosemccollum** [comment]
Hi @v-karl,
Can you try recreating your ABCC package? There should be the full 168 TB in the package, which could be why you are unable to find those files. Let us know if that doesn't fix the issue. Thanks!

**Comment by v-karl** [comment]
Hi @rosemccollum, I recreated the package (this time it had 166TB) and it still gave me the FileNotFoundError. So I tried recreating the package again and it ended up only being 159TB again.

**Comment by v-karl** [comment]
This error seems to be caused by long path names. We managed to download the data on a MacBook but are getting a “Path Too Long Error” when trying to extract the folder with the data on a Windows computer. We’re able to download files that don’t have long path names, but if the path names are too long, we get the ‘File Not Found’ error. 
The NDA-helpdesk suggested trying to enable the “LongPaths” setting on Windows. However, this requires admin access and updating the windows registry (“which if done incorrectly can cause your computer to malfunction”). Another option would be changing the download directory to the root or using a different computer. 
I changed the download directory to make the path as short as possible and was able to download more files this time. Still getting a file not found error for files with the longest names. 
We’re using a Mac now for the download now and that seems to work so far.

**Comment by hough129** [comment]
@v-karl thank you for the update. We also recommend reaching out to the NDA helpdesk, as a lot of others have been experiencing similar issues, and providing your details may help the NDA solve the problem.

I am going to close this issue since you found a way around it, and the NDA is working on fixing it permanently soon. Feel free to re-open it or post another issue with us or the NDA if you continue experiencing issues.
