### ISSUE TITLE
FileNotFoundError and HTTPError arised.

### ISSUE THREAD

**Issue by yermi0626** [DCAN-Labs/nda-abcd-s3-downloader#66]
Hello,
While trying to download the ABCC dataset with this downloader, I encountered a FileNotFoundError and an HTTP error.

The command I tried was : 
`python3 download.py -dp 1220237 -b /remotenas1/ABCC/data_subsets.txt -s /remotenas1/ABCC/subject_list.txt -m /remotenas1/ABCC/metadata/datastructure_manifest.txt -o /remotenas1/ABCC/samples`

The error message was : 
<img width="821" alt="스크린샷 2023-09-14 오후 2 51 29" src="https://github.com/DCAN-Labs/nda-abcd-s3-downloader/assets/81611213/47751043-dfdf-4a6b-9c91-68108ef2b985">

and I'm using Ubuntu 22.04.1 LTS.

For the FileNotFoundError, 
I guess the error has been raised but the files continued to be downloaded anyway, so I wonder if this is not a big problem?
Is there anybody faced this error? I don't really understand what this error means. I guess this is saying that the 'CHANGES.partial' file doesn't exist but I think that's just natural because it was only at the beginning step of downloading files.

And for the HTTPError,
I'm pretty sure that I've followed every necessary step but I'm getting this error anyhow.
I assumed it might just be the problem of the NDA server, but is there any chance I made a mistake while using the download.py or I missed any required steps?

download.py and src, and other files included in the 'nda-abcd-s3-downloader-main' are in my home directory and I'm running this command at home directory.
And I was going to download the ABCC dataset to my remotenas directory.

Could you give me some help? I'll provide any other information needed to resolve this problem. Thank you.

**Comment by hough129** [comment]
@yermi0626, how long ago did you make your data package? I think we experienced a similar error about a month ago due to the NDA updating their security. The solution we found was to create a new data package; then, it worked as expected.

**Comment by yermi0626** [comment]
Hi, @hough129 , well I created the data package about a week ago, and then I encountered an error so I created a new data package again about 1~2 days ago. So it's like I created 3 packages in total - one with the associated data (a week ago), another one without the associated data (a week ago also), and the other with the associated data (1~2 days ago) and I tried to run the download.py with the last one.

**Comment by rosemccollum** [comment]
Hi @yermi0626, this seems to be an ongoing issue with the NDA as our new packages have also stopped working. We suggest that you reach out to them (NDAHelp@mail.nih.gov) about this issue and see what they recommend. You will likely have to recreate your packages once again.

**Comment by yermi0626** [comment]
@rosemccollum , thank you for your reply. I've contacted the NDA help desk and they said they will notify me once the issue is resolved. I'll try to make another package once again anyway. Thank you!

**Comment by fullcream9** [comment]
Hi @yermi0626,
Thank you for your previous efforts!
I've encountered a similar issue as well, 
HTTPError: 504 Server Error: Gateway Time-out for the URL
I’ve attempted to resolve it by switching computers and trying different network environments, but the issue persists. Have you managed to find a solution to this problem, or are you still awaiting a response from NDA?

Moreover, do you think it's possible to use the s3 links from the datastructure_manifest.txt and utilize nda-tools to download the files directly, bypassing the use of DCAN-Labs/nda-abcd-s3-downloader?

Thank you!

**Comment by rosemccollum** [comment]
Hi @yermi0626 and @fullcream9 
We met with a developer from the NDA and he indicated that this issue should be due to the downloader not using the most up to date version of nda-tools. If you reinstall all of the packages in the requirements.txt or update to version 0.2.25 of nda-tools, this issue should resolve. Please let us know if this fix works.

**Comment by yoyo9423** [comment]
I have reinstalled all of tha packages in the new requirements.txt, which resolved the 404 HTTP erros. But I met the following issues: requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url:xxx, when I downloaded the data.

Thank rosemccollum for your updates and looking forward to your further suggestions.

Best

**Comment by rosemccollum** [comment]
Hello @yermi0626 @fullcream9 @yoyo9423 
We have determined that we need to implement the changes from nda-tools 0.2.25 ourselves and are currently working on this implementation. We will update when this fix is ready. Thank you for your patience as we figure this out.

**Comment by fullcream9** [comment]
I appreciate your efforts and look forward to the new version. Thanks again for your assistance and patience throughout this process. @rosemccollum

**Comment by cassandrajustinelowe** [comment]
> Hello @yermi0626 @fullcream9 @yoyo9423 We have determined that we need to implement the changes from nda-tools 0.2.25 ourselves and are currently working on this implementation. We will update when this fix is ready. Thank you for your patience as we figure this out.

By chance, do you happen to have an idea/approximate timeline of when this update may be ready?
