### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error

### ISSUE THREAD

**Issue by yoyo9423** [DCAN-Labs/nda-abcd-s3-downloader#69]
### A short summary of a question you have for the downloader development team.

Dear experts,

I'm sorry to disturb you. I met some problems when I tried to download the derivates from ABCC.
I used the code 'download.py -dp xxx -m xxx1.txt -o output -b xxx2.txt', and then input my NDA username according to the hint. But unluckily, I got the error:
requests.exceptions.HTTPError: 401 Client Error: for url: https://nda.nih.gov/api/package/1220725/files

Could you please give me some suggestions to solve this problem? Many thanks!

**Comment by rosemccollum** [comment]
Hi @yoyo9423 
Please reach out to the NDA (NDAHelp@mail.nih.gov) and let them know about this. You might have to make a new data package and try again.
